# Generated by Django 4.2.23 on 2025-08-02 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(help_text="Supplier's mobile number (10 digits)", max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('daily_capacity', models.FloatField(help_text='Litres the supplier commits to deliver every day')),
                ('total_dairy_cows', models.PositiveIntegerField()),
                ('annual_output', models.FloatField(help_text='Total litres expected in a year')),
                ('distance_from_plant', models.FloatField(help_text='Kilometres from supplier farm to the plant')),
                ('aadhar_number', models.CharField(help_text='Aadhar number of the supplier', max_length=12)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_volume_l', models.FloatField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_url', models.URLField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='MilkLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_l', models.FloatField(default=50.0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('fat_percent', models.FloatField()),
                ('protein_percent', models.FloatField()),
                ('lactose_percent', models.FloatField()),
                ('total_solids', models.FloatField()),
                ('snf', models.FloatField(verbose_name='Solids-Not-Fat')),
                ('urea_nitrogen', models.FloatField(verbose_name='MUN (mg/dL)')),
                ('bacterial_count', models.PositiveIntegerField()),
                ('price_per_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_lots', to='suppliers.paymentbill')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='suppliers.supplier')),
            ],
        ),
    ]
