# Generated by Django 4.2.23 on 2025-08-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_remove_route_suppliers_remove_route_tester'),
        ('suppliers', '0002_milklot_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='distribution.route'),
        ),
    ]
