# Generated by Django 4.2.23 on 2025-08-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_remove_milktransfer_distributor_and_more'),
        ('suppliers', '0003_supplier_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='milklot',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_lots', to='distribution.milktransfer'),
        ),
    ]
