# Generated by Django 4.2.23 on 2025-08-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0001_initial'),
        ('suppliers', '0004_milklot_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='milklot',
            name='bulk_cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_lots', to='collection_center.bulkcooler'),
        ),
    ]
