# Generated by Django 4.2.23 on 2025-08-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_cancollection_onfarmtank_cancollectionlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milklot',
            name='transfer',
        ),
    ]
