# Generated by Django 4.2.23 on 2025-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_remove_milklot_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='milklot',
            name='water_content',
            field=models.FloatField(default=0.0, help_text='Percentage of water in milk. Should ideally be close to natural water content of milk (~87%).'),
        ),
    ]
