# Generated by Django 4.2.23 on 2025-08-12 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_milklot_water_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milklot',
            name='water_content',
        ),
        migrations.AddField(
            model_name='milklot',
            name='added_water_percent',
            field=models.FloatField(default=0.0, help_text='Percentage of water added (adulteration).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
