# Generated by Django 4.2.23 on 2025-08-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_remove_milklot_water_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milklot',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
