# Generated by Django 4.2.23 on 2025-08-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_alter_milklot_price_per_litre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onfarmtank',
            old_name='last_stirred_at',
            new_name='last_calibration_date',
        ),
    ]
