# Generated by Django 4.2.23 on 2025-08-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_rename_last_stirred_at_onfarmtank_last_calibration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancollection',
            name='group_parameter',
        ),
        migrations.RemoveField(
            model_name='cancollection',
            name='group_unit',
        ),
        migrations.RemoveField(
            model_name='cancollection',
            name='group_value',
        ),
        migrations.RemoveField(
            model_name='cancollectionlog',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='cancollectionlog',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='cancollectionlog',
            name='value',
        ),
    ]
