# Generated by Django 4.2.23 on 2025-08-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_employee_role_remove_tester_routes_and_more'),
        ('suppliers', '0012_remove_cancollection_group_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milklot',
            name='tester',
        ),
        migrations.AddField(
            model_name='milklot',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tested_lots', to='plants.employee'),
        ),
    ]
