# Generated by Django 5.2.5 on 2025-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_remove_milklot_tester_milklot_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancollection',
            name='emptied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
