# Generated by Django 5.2.5 on 2025-09-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_cancollection_emptied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onfarmtank',
            name='is_stirred',
            field=models.BooleanField(default=False),
        ),
    ]
