# Generated by Django 5.2.5 on 2025-10-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_onfarmtank_is_stirred'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onfarmtanklog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='onfarmtanklog',
            name='on_farm_tank',
        ),
        migrations.DeleteModel(
            name='CanCollectionLog',
        ),
        migrations.DeleteModel(
            name='OnFarmTankLog',
        ),
    ]
