# Generated by Django 5.2.4 on 2025-07-12 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volume_assigned', models.FloatField()),
                ('distribution_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milk_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='milk.milklot')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='distribution.distributor')),
            ],
            options={
                'ordering': ['distribution_date'],
            },
        ),
    ]
