# Generated by Django 5.2.4 on 2025-07-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='plants.tester'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributors', to='distribution.route'),
        ),
    ]
