# Generated by Django 4.2.23 on 2025-08-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='suppliers',
        ),
        migrations.RemoveField(
            model_name='route',
            name='tester',
        ),
    ]
