# Generated by Django 4.2.23 on 2025-08-07 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0003_supplier_route'),
        ('distribution', '0002_remove_route_suppliers_remove_route_tester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='vehicle_name',
        ),
        migrations.AlterField(
            model_name='distributor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('capacity_liters', models.FloatField(blank=True, null=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='distribution.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='MilkTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='distribution.distributor')),
                ('milk_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_lots', to='suppliers.milklot')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='distribution.route')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='distribution.vehicle')),
            ],
        ),
    ]
