# Generated by Django 4.2.23 on 2025-08-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_remove_distributor_vehicle_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='route',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='distribution.route'),
        ),
    ]
