# Generated by Django 4.2.23 on 2025-08-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_remove_distributor_route_vehicle_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milktransfer',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='milktransfer',
            name='milk_transfer',
        ),
        migrations.AlterField(
            model_name='milktransfer',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_milk_transfers', to='distribution.route'),
        ),
    ]
