# Generated by Django 4.2.23 on 2025-08-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0003_alter_bulkcoolerlog_log_date'),
        ('suppliers', '0007_remove_milklot_transfer'),
        ('distribution', '0005_remove_milktransfer_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milktransfer',
            name='bulk_cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_transfers', to='collection_center.bulkcooler'),
        ),
        migrations.AddField(
            model_name='milktransfer',
            name='can_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_transfers', to='suppliers.cancollection'),
        ),
        migrations.AddField(
            model_name='milktransfer',
            name='on_farm_tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_transfers', to='suppliers.onfarmtank'),
        ),
    ]
