# Generated by Django 4.2.23 on 2025-08-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_alter_batchmembership_unique_together_and_more'),
        ('distribution', '0006_milktransfer_bulk_cooler_milktransfer_can_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milktransfer',
            name='route',
        ),
        migrations.AddField(
            model_name='milktransfer',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='milktransfer',
            name='source_type',
            field=models.CharField(blank=True, choices=[('on_farm_tank', 'On-Farm Tank'), ('bulk_cooler', 'Bulk Cooler'), ('can_collection', 'Can Collection')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='plants.plant'),
        ),
    ]
