# Generated by Django 4.2.23 on 2025-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_remove_milktransfer_route_milktransfer_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milktransfer',
            name='arrival_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milktransfer',
            name='transfer_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
