# Generated by Django 4.2.23 on 2025-08-24 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_plant_contact_person_plant_contact_persons'),
        ('distribution', '0008_milktransfer_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milktransfer',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_as_destination', to='plants.plant'),
        ),
    ]
