# Generated by Django 5.2.5 on 2025-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0006_delete_compositesample'),
        ('distribution', '0009_alter_milktransfer_destination'),
        ('plants', '0007_silo'),
        ('suppliers', '0014_cancollection_emptied_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='milktransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('on_farm_tank__isnull', False)), fields=('on_farm_tank',), name='unique_transfer_per_on_farm_tank'),
        ),
        migrations.AddConstraint(
            model_name='milktransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('bulk_cooler__isnull', False)), fields=('bulk_cooler',), name='unique_transfer_per_bulk_cooler'),
        ),
        migrations.AddConstraint(
            model_name='milktransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('can_collection__isnull', False)), fields=('can_collection',), name='unique_transfer_per_can_collection'),
        ),
    ]
