# Generated by Django 5.2.5 on 2025-09-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_milktransfer_unique_transfer_per_on_farm_tank_and_more'),
        ('plants', '0007_silo'),
    ]

    operations = [
        migrations.AddField(
            model_name='milktransfer',
            name='silo',
            field=models.ForeignKey(blank=True, help_text='The silo this milk is being transferred into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='plants.silo'),
        ),
    ]
