# Generated by Django 5.2.5 on 2025-09-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0011_milktransfer_silo'),
    ]

    operations = [
        migrations.AddField(
            model_name='milktransfer',
            name='emptied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
