# Generated by Django 5.2.5 on 2025-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0012_milktransfer_emptied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milktransfer',
            name='total_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
