# Generated by Django 5.2.5 on 2025-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0013_alter_milktransfer_total_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='milktransfer',
            name='arrival_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of milk (in kg) while arriving at the destination.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='milktransfer',
            name='departure_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of milk (in kg) while leaving the cooperative/source.', max_digits=10, null=True),
        ),
    ]
