# Generated by Django 5.2.5 on 2025-10-05 07:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0014_milktransfer_arrival_weight_kg_and_more'),
        ('milk', '0005_alter_compositesample_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^[0-9]{10,17}$')])),
                ('licence_no', models.CharField(max_length=50)),
                ('licence_expiry', models.DateField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CIPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=50, unique=True)),
                ('wash_type', models.CharField(choices=[('Caustic', 'Caustic'), ('Acid', 'Acid'), ('Sanitiser', 'Sanitiser'), ('Full-CIP', 'Full-CIP')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('expiry_at', models.DateTimeField()),
                ('caustic_temp_c', models.FloatField(blank=True, null=True)),
                ('acid_temp_c', models.FloatField(blank=True, null=True)),
                ('caustic_conc_pct', models.FloatField(blank=True, null=True)),
                ('acid_conc_pct', models.FloatField(blank=True, null=True)),
                ('final_rinse_cond_ms', models.FloatField(blank=True, null=True)),
                ('operator_code', models.CharField(max_length=30)),
                ('passed', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cip_records', to='distribution.vehicle')),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_pass_status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('empty_tare_kg', models.DecimalField(decimal_places=2, help_text='Vehicle + tanker completely empty', max_digits=10)),
                ('net_volume_l', models.DecimalField(decimal_places=2, help_text='Net litres @ standard density', max_digits=10)),
                ('density_kg_per_l', models.DecimalField(decimal_places=4, default=1.032, max_digits=5)),
                ('expected_arrival_plant', models.DateTimeField()),
                ('cip_record', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gate_passes', to='distribution.ciprecord')),
                ('milk_transfer', models.ForeignKey(help_text='The transfer that this pass certifies.', on_delete=django.db.models.deletion.CASCADE, related_name='gate_passes', to='distribution.milktransfer')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='distribution.route')),
            ],
        ),
        migrations.CreateModel(
            name='GatePassQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='True if this pouch travels with the tanker (usually society test).')),
                ('composite_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.compositesample')),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_samples', to='distribution.gatepass')),
            ],
        ),
        migrations.AddField(
            model_name='gatepass',
            name='composite_samples',
            field=models.ManyToManyField(related_name='gate_passes', through='distribution.GatePassQC', to='milk.compositesample'),
        ),
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_no', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(choices=[('top-man', 'Top Man-hole'), ('outlet', 'Outlet Valve'), ('pump-hatch', 'Pump Hatch'), ('instrument-cabinet', 'Instrument Cabinet'), ('sample-cock', 'Sample Cock')], max_length=30)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seals', to='distribution.gatepass')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='gatepass',
            name='driver',
            field=models.ForeignKey(help_text='Driver on record when the pass was issued.', on_delete=django.db.models.deletion.RESTRICT, related_name='gate_passes', to='distribution.vehicledriver'),
        ),
        migrations.AddIndex(
            model_name='ciprecord',
            index=models.Index(fields=['vehicle', '-finished_at'], name='distributio_vehicle_a4c0db_idx'),
        ),
        migrations.AddIndex(
            model_name='ciprecord',
            index=models.Index(fields=['expiry_at'], name='distributio_expiry__4f0c9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gatepassqc',
            unique_together={('gate_pass', 'composite_sample')},
        ),
        migrations.AddConstraint(
            model_name='gatepass',
            constraint=models.UniqueConstraint(condition=models.Q(('gate_pass_status', 'open')), fields=('milk_transfer',), name='unique_open_pass_per_transfer'),
        ),
    ]
