# Generated by Django 5.2.5 on 2025-10-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0015_vehicledriver_ciprecord_gatepass_gatepassqc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledriver',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='vehicledriver',
            name='to_date',
        ),
    ]
