# Generated by Django 5.2.5 on 2025-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0016_remove_vehicledriver_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledriver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
