# Generated by Django 5.2.5 on 2025-10-05 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0017_vehicledriver_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledriver',
            name='mobile',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^[0-9]{10,17}$')]),
        ),
    ]
