# Generated by Django 5.2.5 on 2025-10-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0018_alter_vehicledriver_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledriver',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_drivers', to='distribution.route'),
        ),
    ]
