# Generated by Django 5.2.4 on 2025-07-12 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=50, unique=True)),
                ('volume', models.FloatField()),
                ('storage_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_lots', to='plants.dairyplant')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_lots', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['storage_date'],
            },
        ),
        migrations.CreateModel(
            name='MilkTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fat_content', models.FloatField()),
                ('ph_level', models.FloatField()),
                ('bacterial_count', models.IntegerField()),
                ('water_content', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('milk_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='milk.milklot')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_conducted', to='plants.plantemployee')),
            ],
            options={
                'ordering': ['test_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volume', models.FloatField()),
                ('rate_per_liter', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milk_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='milk.milklot')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='plants.dairyplant')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
