# Generated by Django 4.2.23 on 2025-08-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0008_milktransfer_arrival_datetime_and_more'),
        ('suppliers', '0012_remove_cancollection_group_parameter_and_more'),
        ('collection_center', '0006_delete_compositesample'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_volume_ml', models.PositiveSmallIntegerField(default=50)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('temperature_c', models.FloatField(default=4.0)),
                ('received_at_lab', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('fat_percent', models.FloatField(blank=True, null=True)),
                ('snf_percent', models.FloatField(blank=True, null=True)),
                ('protein_percent', models.FloatField(blank=True, null=True)),
                ('bacterial_count', models.PositiveIntegerField(blank=True, null=True)),
                ('antibiotic_residue', models.BooleanField(default=False)),
                ('added_water_percent', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('bulk_cooler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='collection_center.bulkcooler')),
                ('on_farm_tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='suppliers.onfarmtank')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='distribution.vehicle')),
            ],
        ),
    ]
