# Generated by Django 4.2.23 on 2025-08-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositesample',
            name='passed',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
