# Generated by Django 5.2.5 on 2025-10-02 03:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0013_alter_milktransfer_total_volume'),
        ('milk', '0002_alter_compositesample_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('26.00'), max_digits=8)),
                ('added_water_max', models.FloatField(default=3.0)),
                ('fat_min', models.FloatField(default=3.5)),
                ('fat_bonus', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('snf_min', models.FloatField(default=8.5)),
                ('snf_bonus', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('protein_min', models.FloatField(default=3.0)),
                ('protein_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('urea_max', models.FloatField(default=70.0)),
                ('urea_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('bacteria_max', models.PositiveIntegerField(default=50000)),
                ('bacteria_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('water_penalty_per_percent', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_config', to='distribution.route')),
            ],
        ),
    ]
