# Generated by Django 5.2.5 on 2025-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0003_milkpricingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositesample',
            name='alcohol_test',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compositesample',
            name='cob_test',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compositesample',
            name='mbtr_quick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compositesample',
            name='ph_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compositesample',
            name='sample_type',
            field=models.CharField(choices=[('instant-gate tests', 'Instant-Gate Tests'), ('society test', 'Society Test')], default='society test', max_length=20),
        ),
    ]
