# Generated by Django 5.2.5 on 2025-10-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0014_milktransfer_arrival_weight_kg_and_more'),
        ('milk', '0004_compositesample_alcohol_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositesample',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateSamples', to='distribution.vehicle'),
        ),
    ]
