# Generated by Django 5.2.4 on 2025-07-19 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_volume_l', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_by_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BatchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_l', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.batch')),
                ('milk_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.milklot')),
            ],
            options={
                'unique_together': {('batch', 'milk_lot')},
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='lots',
            field=models.ManyToManyField(through='plants.BatchMembership', to='suppliers.milklot'),
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(default='Milk Quality Tester', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
