# Generated by Django 4.2.23 on 2025-08-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_remove_route_suppliers_remove_route_tester'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='testers', to='distribution.route'),
        ),
    ]
