# Generated by Django 4.2.23 on 2025-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_tester_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Daily processing capacity in liters', max_digits=10)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Mark inactive if plant is closed or not in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='batchmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='batchmembership',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batchmembership',
            name='milk_lot',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='BatchMembership',
        ),
    ]
