# Generated by Django 4.2.23 on 2025-08-23 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_remove_milklot_tester_milklot_employee'),
        ('distribution', '0008_milktransfer_arrival_datetime_and_more'),
        ('plants', '0004_employee_role_remove_tester_routes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tester',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='plants.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='employees', to='distribution.route'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
