# Generated by Django 4.2.23 on 2025-08-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_delete_tester_employee_role_employee_routes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='plant',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, help_text='Select one or more employees who are contact persons for this plant.', related_name='plants_as_contact', to='plants.employee'),
        ),
    ]
