# Generated by Django 5.2.5 on 2025-08-31 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_plant_contact_person_plant_contact_persons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('capacity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('milk_type', models.CharField(choices=[('raw', 'Raw Milk'), ('pasteurized', 'Pasteurized'), ('standardized', 'Standardized'), ('skim', 'Skim Milk'), ('cream', 'Cream')], default='raw', max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('filling', 'Filling'), ('full', 'Full'), ('draining', 'Draining'), ('cleaning', 'Cleaning'), ('offline', 'Offline')], default='empty', max_length=20)),
                ('is_clean', models.BooleanField(default=True)),
                ('last_cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_cleaned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
