# Generated by Django 5.2.5 on 2025-09-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_silo'),
    ]

    operations = [
        migrations.AddField(
            model_name='silo',
            name='transfer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
