# Generated by Django 5.2.5 on 2025-09-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_silo_transfer_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silo',
            name='transfer_count',
        ),
    ]
