# Generated by Django 4.2.23 on 2025-08-09 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0005_remove_milktransfer_distributor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cooler-1, Cooler-2 …', max_length=50)),
                ('capacity_liters', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(5000)])),
                ('current_volume_liters', models.FloatField(default=0.0)),
                ('temperature_celsius', models.FloatField(default=4.0, help_text='Current temperature in °C', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(8.0)])),
                ('last_stirred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(help_text='Collection centre / BMCU where this cooler is installed.', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_coolers', to='distribution.route')),
            ],
        ),
        migrations.CreateModel(
            name='CompositeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField(auto_now_add=True)),
                ('fat_percent', models.FloatField(blank=True, null=True)),
                ('snf_percent', models.FloatField(blank=True, null=True)),
                ('protein_percent', models.FloatField(blank=True, null=True)),
                ('bacterial_count', models.PositiveIntegerField(blank=True, null=True)),
                ('antibiotic_residue', models.BooleanField(default=False, help_text='True if β-lactams or other residues detected.')),
                ('added_water', models.BooleanField(default=False)),
                ('passed', models.BooleanField(null=True)),
                ('bulk_cooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_samples', to='collection_center.bulkcooler')),
                ('transfer', models.OneToOneField(blank=True, help_text='Linked once the tanker is actually loaded.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composite_sample', to='distribution.milktransfer')),
            ],
        ),
    ]
