# Generated by Django 4.2.23 on 2025-08-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcooler',
            name='emptied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcooler',
            name='filled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcooler',
            name='last_cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcooler',
            name='last_sanitized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcooler',
            name='last_serviced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkcooler',
            name='service_interval_days',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.CreateModel(
            name='BulkCoolerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('volume_liters', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('emptied_at', models.DateTimeField(blank=True, null=True)),
                ('last_cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('last_sanitized_at', models.DateTimeField(blank=True, null=True)),
                ('last_stirred_at', models.DateTimeField(blank=True, null=True)),
                ('last_serviced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_cooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='collection_center.bulkcooler')),
            ],
            options={
                'unique_together': {('bulk_cooler', 'log_date')},
            },
        ),
    ]
