# Generated by Django 4.2.23 on 2025-08-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0002_bulkcooler_emptied_at_bulkcooler_filled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkcoolerlog',
            name='log_date',
            field=models.DateTimeField(),
        ),
    ]
