# Generated by Django 4.2.23 on 2025-08-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0003_alter_bulkcoolerlog_log_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkcooler',
            old_name='last_stirred_at',
            new_name='last_calibration_date',
        ),
    ]
