# Generated by Django 4.2.23 on 2025-08-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0004_rename_last_stirred_at_bulkcooler_last_calibration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkcoolerlog',
            old_name='last_stirred_at',
            new_name='last_calibration_date',
        ),
    ]
