# Generated by Django 4.2.23 on 2025-08-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0005_rename_last_stirred_at_bulkcoolerlog_last_calibration_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompositeSample',
        ),
    ]
