# Generated by Django 5.2.5 on 2025-09-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_center', '0006_delete_compositesample'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcooler',
            name='is_stirred',
            field=models.BooleanField(default=False),
        ),
    ]
