# Generated by Django 5.2.5 on 2025-10-20 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0016_alter_onfarmtanklog_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkPaymentInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(db_index=True)),
                ('invoice_prefix', models.CharField(default='MLK/', max_length=50)),
                ('invoice_num', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('cancel_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount_paid', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], db_index=True, default='pending', max_length=15)),
                ('invoice_paid_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_payment_invoices', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'milk_payment_invoice',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MilkPaymentInvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty_l', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.milkpaymentinvoice')),
                ('milk_lot', models.OneToOneField(limit_choices_to={'status': 'approved'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_item', to='suppliers.milklot')),
            ],
            options={
                'db_table': 'milk_payment_invoice_item',
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='milkpaymentinvoice',
            index=models.Index(fields=['supplier', '-invoice_date'], name='milk_paymen_supplie_8cb41a_idx'),
        ),
        migrations.AddIndex(
            model_name='milkpaymentinvoice',
            index=models.Index(fields=['payment_status', '-invoice_date'], name='milk_paymen_payment_dc9a98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milkpaymentinvoice',
            unique_together={('supplier', 'invoice_date')},
        ),
    ]
